gText_Birch_Welcome::
	.string "ça tourne\p"
	.string "Bonjour, je me présente, je suis\p"
	.string "Le professeur Shwartz.\p"
	.string "Demain, est le grand jour. Trois\n"
	.string "personnes viendront au fameux CDC,\p"
	.string "Comme à chaque année, ces trois\n"
	.string "personnes auront le droit à un\p"
	.string "Pokémon rare de leur choix.\n"
	.string "De plus, ils visiteront (rapidement)\p"
	.string "Le CDC. Ce seront les seules personnes\n"
	.string "qui visiteront le CDC cette année hors\p"
	.string "Hors personnel.\n"
	.string ".... .... ..... ..... ......\p"
	.string "\n"
	.string "$"

gText_Birch_Pokemon::
	.string "Ceci est ce que l'on appelle Pokémon.\p"
	.string "En plus, ils obtiendront un Pokédex\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Le CDC, rappelons le est l'un des plus\n"
	.string "grands laboratoires destiné à l'étude des\p"
	.string "Pokémon à l'international. Bien entendu\n"
	.string "personne n'accède au CDC, étant donné\l"
	.string "que l'on y fait des recherches secrètes\p"
	.string "et c'est un havre de paix pour des espèces\n"
	.string "de Pokémon en voie d'extinction.\p"
	.string "Bien. Maintenant je vais vour présenter\n"
	.string "Ces trois privilégiés, le premier a\p"
	.string "avoir eu son pass est un garçon, originaire\n"
	.string "de Portokov, du nom de Daniel, la deuxième\p"
	.string "une fille du nom de Lisa, originaire de\n"
	.string "la Ville-Monde. Et, en dernier\l"
	.string ".. ... ....... ......\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "... C'est une fille ou un garçon?\n"
	.string "J'ai pas assez révisé mon texte.$"

gText_Birch_WhatsYourName::
	.string "Euhm, oui et, son nom est\n"
	.string "... euh... $"

gText_Birch_SoItsPlayer::
	.string "{PLAYER}{KUN} ?$"

gText_Birch_YourePlayer::
	.string "Je disais, cette troisième personne\p"
	.string "Est {PLAYER}{KUN}, un habitant de la\n"
	.string "périphérie de Cellapolis. Bien.\l"
	.string "Ceci conclut cette émission.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Journaliste : Merci à vous P.Shwartz\p"
	.string "Je m'occupe de résumer, trois jeunes\n"
	.string "personnes accèderont demain au prestigieux\p"
	.string "CDC et obtiendront un Pokémon rare, un\n"
	.string "Pokédex et des objets spéciaux. Merci de\l"
	.string "votre écoute, c'était Caroline Redoux\p"
	.string "Rendez-vous demain même heure même chaîne.\n"
	.string "...\p"
	.string "$"
