gText_ObtainedTheItem::
	.string "Vous avez reçu {STR_VAR_2}!$"

gText_TheBagIsFull::
	.string "Le sac est plein…$"

gText_PutItemInPocket::
	.string "{PLAYER} put away the {STR_VAR_2}\n"
	.string "in the {STR_VAR_3} POCKET.$"

gText_PlayerFoundOneItem::
	.string "{PLAYER} a trouvé un(e) {STR_VAR_2}!$"

gText_TooBadBagIsFull::
	.string "Mince!\n"
	.string "Le sac est plein…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} put away the {STR_VAR_2}\n"
	.string "in the BAG.$"

gText_ObtainedTheDecor::
	.string "Obtained the {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
	.string "Too bad! There's no room left for\n"
	.string "another {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "{STR_VAR_2} est transféré\n"
	.string "dans les boîtes PC.$"
