	.align 2
gText_ConfirmSave::
	.string "Sauvegarder la partie?$"

gText_AlreadySavedFile::
	.string "Il y a une autre sauvegarde.\n"
	.string "Écraser les données ?$"

gText_SavingDontTurnOff::
	.string "Sauvegarde en cours…\n"
	.string "Ne pas éteindre.$"

gText_PlayerSavedGame::
	.string "{PLAYER} a sauvegardé la partie.$"

gText_DifferentSaveFile::
	.string "ATTENTION!\p"
	.string "Vous avez une autre sauvegarde\n"
	.string "En cours.\p"
	.string "Si vous sauvegardez à ce stade\n"
	.string "vous perderez toutes vos données\l"
	.string "Pokéomn, Objets, Surnoms...\p"
	.string "Vous êtes sûrs de vouloir sauvegarder\n"
	.string "et supprimer vos données précédentes ?$"

gText_SaveError::
	.string "ERREUR!\p"
	.string "https://discord.gg/jemEuB3pMJ\n"
	.string "Demandez de l'aide ici.$"

gText_SavingDontTurnOffPower::
	.string "Sauvegarde…\n"
	.string "Ne pas éteindre.$"
